 --Rank games having most number of players
 select *,
 RANK() over(order by NoOfPlayers DESC) 'Rank'
 from(
 SELECT 
 GameID,
 GameName,
 COUNT(distinct UserID) 'NoOfPlayers' 
 from #quickaccess
 group by GameID,GameName)t1;


  --Rank countries having most number of players
select *,
RANK() over(order by NoOfPlayers DESC) 'Rank'
from(
SELECT 
Country,
COUNT(distinct UserID) 'NoOfPlayers' 
from #quickaccess
group by Country)t1;


--Show age of player playing a certain game
SELECT
GameID,
GameName,
(Age)  'Average Age'
from 
#quickaccess
group by GameID,GameName;



--TOTAL TIME SPENT BY PLAYER ON A GAME AS PER RECORDS

 select 
	GameID,
	UserID,
	UserName,
	SUM(DATEDIFF(MINUTE,SessionStart,SessionEnd)) 'SessionDuration'
	--,DATEDIFF(HOUR,RegistrationDate,SessionStart) 'DedicatedTime'
 from #quickaccess
 GROUP BY GameID,
		  UserID,
		  UserName;

--averagae session length?

 select 
	GameID,
	UserID,
	UserName,
	avg(DATEDIFF(MINUTE,SessionStart,SessionEnd)) 'SessionDuration'
	--,DATEDIFF(HOUR,RegistrationDate,SessionStart) 'DedicatedTime'
 from #quickaccess
 GROUP BY GameID,
		  UserID,
		  UserName;

--DAU
select
	GameID,
	GameName,
	DATETRUNC(DAy,SessionStart) 'Daily',
	COUNT(UserID) 'SESSIONCount',
	COUNT(distinct UserID) 'USERCount'
from #quickaccess
GROUP BY GameID,GameName,DATETRUNC(DAy,SessionStart)
ORDER BY GameID,DATETRUNC(DAy,SessionStart);



-- rank Total REVENUE generated by games
select 
	*,
	dense_rank() over(order by TotalRevenue desc) 'Rank'
from 
	(select
		g.GameID,
		g.GameName,
		sum(Amount) 'TotalRevenue'
	from Purchases p
	join Games g on p.GameID=g.GameID
	group by g.GameID,g.GameName)t1;



--rank by PLAYER FEEDBACK SCORES
select 
	g.GameID,
	avg(Score) 'Score',
	rank() over(order by avg(Score) desc) 'Rank'
from Feedback f 
right join users u on u.UserID=f.UserID
right join Games g on g.GameID=f.GameID
group by g.GameID;


--No of user by platform
select 
	[GameName],
	[platform],
	COUNT(distinct UserID) 'NoOfUser' 
from #quickaccess 
group by [GameName],[platform];




--ENGAGEMENT ACTIVITY TIMELINE
select 
	g.GameID,
	GameName,
	DATETRUNC(DAY,EngagementDate) 'Date',
	sum(f.InvitesCount) 'No of Invites',
	sum(f.SharesCount) 'No of Shares'

from SocialEngagements f
right join users u on u.UserID=f.UserID
right join Games g on g.GameID=f.GameID
group by g.GameID,GameName,DATETRUNC(DAY,EngagementDate) 
order by 1,3;